### ISSUE TITLE
Example to use in TabBarViewController

### ISSUE THREAD

**Issue by indrajitsinh** [DigitalLeaves/DLHamburguerMenu#16]
does it works with TabBarViewController ? 
if so could you please provide an example of it 
Thank you

**Comment by DigitalLeaves** [comment]
Yes, it works. You just need to specify a UITabBarController as the root of your hierarchy. Instead of having a DLHamburguerNavigationController/UINavigationController and using:

```
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {

        let nvc = self.mainNavigationController()
        if let hamburguerViewController = self.findHamburguerViewController() {
            hamburguerViewController.hideMenuViewControllerWithCompletion({ () -> Void in
                nvc.visibleViewController?.performSegue(withIdentifier: self.segues[(indexPath as NSIndexPath).row], sender: nil)
                hamburguerViewController.contentViewController = nvc
            })
        }
    }
```

You should invoke your setSelectedIndex of your UITabBarController. I don't have time for writing a full fledged example, but should be pretty straightforward. If you run into a specific problem because of DLHamburguerMenu, let me know. 

Good luck!
